server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:11000/eureka/

spring:
  application:
    name: p2p_payservice

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/p2p?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bawei.entity
  configuration:
      map-underscore-to-camel-case: false
mapper:
  style: normal
logging:
  level:
    com.bawei.mapper: debug